class ModelSpecifications {
  const ModelSpecifications({
    required this.releaseYear,
    required this.chip,
    required this.displaySize,
    required this.displayTechnology,
    required this.proMotion,
    required this.maximumRefreshRate,
    required this.biometricFamily,
    required this.cameraFamily,
    required this.connector,
    this.expectedRam,
  });
  final int releaseYear;
  final String chip;
  final String displaySize;
  final String displayTechnology;
  final bool proMotion;
  final int maximumRefreshRate;
  final String biometricFamily;
  final String cameraFamily;
  final String connector;
  final String? expectedRam;

  static const byIdentifier = <String, ModelSpecifications>{
    'iPhone17,1': ModelSpecifications(
      releaseYear: 2024,
      chip: 'A18 Pro',
      displaySize: '6.3 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone17,2': ModelSpecifications(
      releaseYear: 2024,
      chip: 'A18 Pro',
      displaySize: '6.9 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone18,1': ModelSpecifications(
      releaseYear: 2025,
      chip: 'A19 Pro',
      displaySize: '6.3 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone18,2': ModelSpecifications(
      releaseYear: 2025,
      chip: 'A19 Pro',
      displaySize: '6.9 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone19,2': ModelSpecifications(
      releaseYear: 2026,
      chip: 'A20 Pro',
      displaySize: '6.3 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone19,3': ModelSpecifications(
      releaseYear: 2026,
      chip: 'A20 Pro',
      displaySize: '6.9 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone19,7': ModelSpecifications(
      releaseYear: 2026,
      chip: 'A20 Pro',
      displaySize: '6.9 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone16,1': ModelSpecifications(
      releaseYear: 2023,
      chip: 'A17 Pro',
      displaySize: '6.1 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone16,2': ModelSpecifications(
      releaseYear: 2023,
      chip: 'A17 Pro',
      displaySize: '6.7 in',
      displayTechnology: 'OLED',
      proMotion: true,
      maximumRefreshRate: 120,
      biometricFamily: 'Face ID',
      cameraFamily: 'Pro camera system',
      connector: 'USB-C',
    ),
    'iPhone15,4': ModelSpecifications(
      releaseYear: 2023,
      chip: 'A16 Bionic',
      displaySize: '6.1 in',
      displayTechnology: 'OLED',
      proMotion: false,
      maximumRefreshRate: 60,
      biometricFamily: 'Face ID',
      cameraFamily: 'Dual camera system',
      connector: 'USB-C',
    ),
    'iPhone15,5': ModelSpecifications(
      releaseYear: 2023,
      chip: 'A16 Bionic',
      displaySize: '6.7 in',
      displayTechnology: 'OLED',
      proMotion: false,
      maximumRefreshRate: 60,
      biometricFamily: 'Face ID',
      cameraFamily: 'Dual camera system',
      connector: 'USB-C',
    ),
  };
}
